# Generated by Django 4.1.1 on 2023-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("restaurant_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("items", models.ManyToManyField(to="search.item")),
            ],
        ),
    ]
