# Generated by Django 4.1.1 on 2023-06-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.CharField(max_length=255),
        ),
    ]
